Mounting the bronze container of storage account & fetching data fr it.

In [0]:

dbutils.fs.mount(
  source = "wasbs://bronze@capstonestorage23.blob.core.windows.net",
  mount_point = '/mnt/caps',
  extra_configs = {
    'fs.azure.account.key.capstonestorage23.blob.core.windows.net':'uylHIUmwWqk2jdvsKQyAsd8ei2GDTnnvI7KT0JN0LRd4V/uFWoRd1jiayjDIprn2AX7jF9nrdoOR+ASt+NzuwQ=='
  }
)

Checking File Info

In [0]:
dbutils.fs.ls('/mnt/caps')

In [0]:
!pip install pyspark

Reading CSV File_ _ city_day

In [0]:

df = spark.read.csv('/mnt/caps/city_day.csv', header = True)
df.show()

Importing spark

In [0]:
from pyspark.sql import SparkSession

null_spark = SparkSession.builder.appName('Handling Missing values using PySpark').getOrCreate()
null_spark

Reading file & checking Schema.

In [0]:
df_null_capstone = null_spark.read.csv('/mnt/caps/city_day.csv', header = True, inferSchema = True)
df_null_capstone

Initial Dataset.

In [0]:
df_null_capstone.show()

In [0]:
df_null_capstone.describe().show()

Initial City Column Properties.

In [0]:
df_null_capstone.describe('City').show()

Calculating total column length of the dataset.

In [0]:
cols=len(df_null_capstone.columns)
cols

In [0]:
df_null_capstone.toPandas().info()

Copying DataFrame in df Variable.

In [0]:
df = df_null_capstone.toPandas().copy()

In [0]:
df

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,None
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,None
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,None
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,None
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29526,Visakhapatnam,2020-06-27,15.02,50.94,7.68,25.06,19.54,12.47,0.47,8.55,23.30,2.24,12.07,0.73,41.0,Good
29527,Visakhapatnam,2020-06-28,24.38,74.09,3.42,26.06,16.53,11.99,0.52,12.72,30.14,0.74,2.21,0.38,70.0,Satisfactory
29528,Visakhapatnam,2020-06-29,22.91,65.73,3.45,29.53,18.33,10.71,0.48,8.42,30.96,0.01,0.01,0.00,68.0,Satisfactory
29529,Visakhapatnam,2020-06-30,16.64,49.97,4.05,29.26,18.80,10.03,0.52,9.84,28.30,0.00,0.00,0.00,54.0,Satisfactory
29530,Visakhapatnam,2020-07-01,15.00,66.00,0.40,26.85,14.05,5.20,0.59,2.10,17.05,NaN,NaN,NaN,50.0,Good

Importing Pandas Library

In [0]:
import pandas as pd 
import numpy as  np
import matplotlib.pyplot as plt

In [0]:
%matplotlib inline

In [0]:
df = pd.DataFrame(df)

In [0]:
df.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,None
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,None
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,None
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,None
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,None

Data Cleaning Starts from here.

In [0]:
del df['Xylene']

In [0]:
df.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,NaN,None
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,NaN,None
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,NaN,None
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,NaN,None
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,NaN,None

In [0]:
df.describe()

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,AQI
count,24933.000000,18391.000000,25949.000000,25946.000000,25346.000000,19203.000000,27472.000000,25677.000000,25509.000000,23908.000000,21490.000000,24850.000000
mean,67.450578,118.127103,17.574730,28.560659,32.309123,23.483476,2.248598,14.531977,34.491430,3.280840,8.700972,166.463581
std,64.661449,90.605110,22.785846,24.474746,31.646011,25.684275,6.962884,18.133775,21.694928,15.811136,19.969164,140.696585
min,0.040000,0.010000,0.020000,0.010000,0.000000,0.010000,0.000000,0.010000,0.010000,0.000000,0.000000,13.000000
25%,28.820000,56.255000,5.630000,11.750000,12.820000,8.580000,0.510000,5.670000,18.860000,0.120000,0.600000,81.000000
50%,48.570000,95.680000,9.890000,21.690000,23.520000,15.850000,0.890000,9.160000,30.840000,1.070000,2.970000,118.000000
75%,80.590000,149.745000,19.950000,37.620000,40.127500,30.020000,1.450000,15.220000,45.570000,3.080000,9.150000,208.000000
max,949.990000,1000.000000,390.680000,362.210000,467.630000,352.890000,175.810000,193.860000,257.730000,455.030000,454.850000,2049.000000

In [0]:
df.info()

In [0]:
df1 = df.copy()

Removing the row which contains all  Null Value.

In [0]:
df1.dropna(axis=0, how='all', thresh=4, subset=None, inplace=False)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,NaN,None
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,NaN,None
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,NaN,None
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,NaN,None
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29526,Visakhapatnam,2020-06-27,15.02,50.94,7.68,25.06,19.54,12.47,0.47,8.55,23.30,2.24,12.07,41.0,Good
29527,Visakhapatnam,2020-06-28,24.38,74.09,3.42,26.06,16.53,11.99,0.52,12.72,30.14,0.74,2.21,70.0,Satisfactory
29528,Visakhapatnam,2020-06-29,22.91,65.73,3.45,29.53,18.33,10.71,0.48,8.42,30.96,0.01,0.01,68.0,Satisfactory
29529,Visakhapatnam,2020-06-30,16.64,49.97,4.05,29.26,18.80,10.03,0.52,9.84,28.30,0.00,0.00,54.0,Satisfactory
29530,Visakhapatnam,2020-07-01,15.00,66.00,0.40,26.85,14.05,5.20,0.59,2.10,17.05,NaN,NaN,50.0,Good

In [0]:
df1.info()

Data cleaning for the column which contains max null value.

In [0]:
df1 = df1.dropna(thresh=len(df1.columns)-1)

In [0]:
df1.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,AQI,AQI_Bucket
1595,Ahmedabad,2019-05-15,37.55,122.41,15.08,85.12,58.72,NaN,15.08,163.01,48.23,16.44,85.54,281.0,Poor
1596,Ahmedabad,2019-05-16,33.97,116.32,14.67,79.71,55.61,NaN,14.67,91.26,51.86,15.55,83.89,330.0,Very Poor
1597,Ahmedabad,2019-05-17,35.48,130.07,18.02,77.61,58.41,NaN,18.02,98.35,38.99,15.88,83.83,356.0,Very Poor
1598,Ahmedabad,2019-05-18,34.11,138.31,13.27,75.23,51.83,NaN,13.27,88.66,42.22,15.93,82.73,359.0,Very Poor
1599,Ahmedabad,2019-05-19,33.69,111.73,34.56,68.90,69.77,NaN,34.56,80.90,36.95,15.53,84.17,547.0,Severe

In [0]:
df1.info()

Replacing all the null Values with mean value.

In [0]:

df1=df1.fillna(df1.mean())

In [0]:
df1.info()

In [0]:
df1.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,67.450578,118.127103,0.92,18.22,17.15,23.483476,0.92,27.64,133.36,0.00,0.02,166.463581,None
1,Ahmedabad,2015-01-02,67.450578,118.127103,0.97,15.69,16.46,23.483476,0.97,24.55,34.06,3.68,5.50,166.463581,None
2,Ahmedabad,2015-01-03,67.450578,118.127103,17.40,19.30,29.70,23.483476,17.40,29.07,30.70,6.80,16.40,166.463581,None
3,Ahmedabad,2015-01-04,67.450578,118.127103,1.70,18.48,17.97,23.483476,1.70,18.59,36.08,4.43,10.14,166.463581,None
4,Ahmedabad,2015-01-05,67.450578,118.127103,22.10,21.42,37.76,23.483476,22.10,39.33,39.31,7.01,18.89,166.463581,None

In [0]:
df1.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,AQI,AQI_Bucket,DATE
1595,Ahmedabad,2019-05-15,37.55,122.41,15.08,85.12,58.72,25.249129,15.08,163.01,48.23,16.44,85.54,281.0,Poor,2019-05-15
1596,Ahmedabad,2019-05-16,33.97,116.32,14.67,79.71,55.61,25.249129,14.67,91.26,51.86,15.55,83.89,330.0,Very Poor,2019-05-16
1597,Ahmedabad,2019-05-17,35.48,130.07,18.02,77.61,58.41,25.249129,18.02,98.35,38.99,15.88,83.83,356.0,Very Poor,2019-05-17
1598,Ahmedabad,2019-05-18,34.11,138.31,13.27,75.23,51.83,25.249129,13.27,88.66,42.22,15.93,82.73,359.0,Very Poor,2019-05-18
1599,Ahmedabad,2019-05-19,33.69,111.73,34.56,68.90,69.77,25.249129,34.56,80.90,36.95,15.53,84.17,547.0,Severe,2019-05-19

Importing datetime

In [0]:
 
from datetime import datetime

Adding three seprate columns as year, month & day by taking reference from Date column.

In [0]:

import datetime as dt
df1['day'] = df1['Date'].dt.day
df1['month'] = df1['Date'].dt.month
df1['year'] = df1['Date'].dt.year

In [0]:
df1.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,AQI,AQI_Bucket,day,month,year
0,Ahmedabad,2015-01-01,67.450578,118.127103,0.92,18.22,17.15,23.483476,0.92,27.64,133.36,0.00,0.02,166.463581,None,1,1,2015
1,Ahmedabad,2015-01-02,67.450578,118.127103,0.97,15.69,16.46,23.483476,0.97,24.55,34.06,3.68,5.50,166.463581,None,2,1,2015
2,Ahmedabad,2015-01-03,67.450578,118.127103,17.40,19.30,29.70,23.483476,17.40,29.07,30.70,6.80,16.40,166.463581,None,3,1,2015
3,Ahmedabad,2015-01-04,67.450578,118.127103,1.70,18.48,17.97,23.483476,1.70,18.59,36.08,4.43,10.14,166.463581,None,4,1,2015
4,Ahmedabad,2015-01-05,67.450578,118.127103,22.10,21.42,37.76,23.483476,22.10,39.33,39.31,7.01,18.89,166.463581,None,5,1,2015

In [0]:
df1.info()

Deleting Date column.

In [0]:

del df1['Date']

In [0]:
df1.head(100)

,City,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,AQI,AQI_Bucket,day,month,year
0,Ahmedabad,67.450578,118.127103,0.92,18.22,17.15,23.483476,0.92,27.64,133.36,0.00,0.02,166.463581,None,1,1,2015
1,Ahmedabad,67.450578,118.127103,0.97,15.69,16.46,23.483476,0.97,24.55,34.06,3.68,5.50,166.463581,None,2,1,2015
2,Ahmedabad,67.450578,118.127103,17.40,19.30,29.70,23.483476,17.40,29.07,30.70,6.80,16.40,166.463581,None,3,1,2015
3,Ahmedabad,67.450578,118.127103,1.70,18.48,17.97,23.483476,1.70,18.59,36.08,4.43,10.14,166.463581,None,4,1,2015
4,Ahmedabad,67.450578,118.127103,22.10,21.42,37.76,23.483476,22.10,39.33,39.31,7.01,18.89,166.463581,None,5,1,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Ahmedabad,120.960000,118.127103,4.23,20.86,25.02,23.483476,4.23,35.54,35.66,6.05,15.85,303.000000,Very Poor,6,4,2015
96,Ahmedabad,138.630000,118.127103,5.65,25.47,30.67,23.483476,5.65,87.43,29.77,11.25,24.67,314.000000,Very Poor,7,4,2015
97,Ahmedabad,144.360000,118.127103,15.82,30.69,46.10,23.483476,15.82,66.39,27.34,17.22,49.56,378.000000,Very Poor,8,4,2015
98,Ahmedabad,85.030000,118.127103,3.30,26.70,27.41,23.483476,3.30,59.16,35.89,7.58,29.19,415.000000,Severe,9,4,2015
99,Ahmedabad,134.600000,118.127103,5.90,26.27,28.70,23.483476,5.90,34.53,7.00,0.00,0.00,166.463581,None,10,4,2015

In [0]:
df1.day.unique()

mounting the silver container of storage account & Fetching data from it to perform aggregate function.

In [0]:

dbutils.fs.mount(
  source = "wasbs://silver@capstonestorage23.blob.core.windows.net",
  mount_point = '/mnt/sl',
  extra_configs = {
    'fs.azure.account.key.capstonestorage23.blob.core.windows.net':'uylHIUmwWqk2jdvsKQyAsd8ei2GDTnnvI7KT0JN0LRd4V/uFWoRd1jiayjDIprn2AX7jF9nrdoOR+ASt+NzuwQ=='
  }
)

In [0]:
sparkDF=spark.createDataFrame(df1)

Storing Clean data in Silver Container in a file name as finaltestoutput

In [0]:

sparkDF.coalesce(1).write.format("com.databricks.spark.csv").option("header", "true").mode("overwrite").save("/mnt/sl/finaltestoutput.csv")

In [0]:
df1.info()

Aggregate Function.....
#Calculating sum of CO column with respect to city.

In [0]:


CO_Sum = df1.groupby("AQI_Bucket",as_index=False).agg(
    {"CO": np.sum, "City": pd.Series.nunique})

In [0]:
CO_Sum.head()

,AQI_Bucket,CO,City
0,Good,769.223089,23
1,Moderate,11526.092535,25
2,Poor,6398.232062,22
3,Satisfactory,6632.088232,26
4,Severe,25008.266357,13

Calculating Avg of CO by grouping w.r.t. AQI_BUCKET

In [0]:
.
CO_Avg = df1.groupby("AQI_Bucket",as_index=False).agg(
    {"CO": np.mean, "City": pd.Series.nunique})

In [0]:
CO_Avg=spark.createDataFrame(CO_Avg)

In [0]:
CO_Avg.head()

,AQI_Bucket,CO,City
0,Good,0.573619,23
1,Moderate,1.305481,25
2,Poor,2.300695,22
3,Satisfactory,0.806431,26
4,Severe,18.690782,13

Calculating Avg of NH3 by grouping it w.r.t to AQI_BUCKET.

In [0]:

NH3_Avg = df1.groupby("AQI_Bucket",as_index=False).agg(
    {"NH3": np.mean, "City": pd.Series.nunique})

In [0]:
NH3_Avg=spark.createDataFrame(NH3_Avg)

In [0]:
NH3_Avg.tail()

,NH3,City
AQI_Bucket,,
Moderate,25.566088,22
Poor,30.601941,19
Satisfactory,21.438617,23
Severe,42.614773,12
Very Poor,38.122960,17

Calculating Avg of AQI by grouping it w.r.t to AQI_BUCKET

In [0]:

AQI_Avg = df1.groupby("AQI_Bucket",as_index=False).agg(
    {"AQI": np.mean})

In [0]:
AQI_Avg.head()

,AQI
AQI_Bucket,
Good,40.305720
Moderate,135.736535
Poor,247.066318
Satisfactory,76.683205
Severe,496.209256

Calculating Avg of AQI w.r.t year.

In [0]:

year = df1.groupby("year",as_index=False).agg(
    {"AQI": np.mean, "City": pd.Series.nunique})

In [0]:
year.head()

,AQI,City
year,,
2015,216.743836,4
2016,172.539787,5
2017,169.112401,11
2018,150.724392,13
2019,145.283315,20

Calculating Avg of AQI w.r.t month.

In [0]:

month = df1.groupby("month",as_index=False).agg(
    {"AQI": np.mean, "City": pd.Series.nunique})

In [0]:
month.head()

,AQI,City
month,,
1,205.948276,22
2,175.272109,22
3,137.740606,23
4,121.457219,23
5,126.660521,22

Fetching the data according to Ahmedabad Location.

In [0]:

ahmedabad = df1.loc[df['City'] == 'Ahmedabad']

In [0]:
ahmedabad.head()

,City,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,AQI,AQI_Bucket,day,month,year
0,Ahmedabad,67.450578,118.127103,0.92,18.22,17.15,23.483476,0.92,27.64,133.36,0.00,0.02,166.463581,None,1,1,2015
1,Ahmedabad,67.450578,118.127103,0.97,15.69,16.46,23.483476,0.97,24.55,34.06,3.68,5.50,166.463581,None,2,1,2015
2,Ahmedabad,67.450578,118.127103,17.40,19.30,29.70,23.483476,17.40,29.07,30.70,6.80,16.40,166.463581,None,3,1,2015
3,Ahmedabad,67.450578,118.127103,1.70,18.48,17.97,23.483476,1.70,18.59,36.08,4.43,10.14,166.463581,None,4,1,2015
4,Ahmedabad,67.450578,118.127103,22.10,21.42,37.76,23.483476,22.10,39.33,39.31,7.01,18.89,166.463581,None,5,1,2015

Fetching the data according to Amaravati Location.

In [0]:

Amaravati = df1.loc[df['City'] == 'Amaravati']

Calculating average of AQI for Amaravati city per year.

In [0]:

Amaravati_year = Amaravati.groupby("year",as_index=False).agg(
    {"AQI": np.mean})

In [0]:
Amaravati_year.head()

,AQI
year,
2017,192.513514
2018,102.113402
2019,98.485437
2020,60.061111

Mounting the gold container of storage account & storing data in it.

In [0]:

dbutils.fs.mount(
  source = "wasbs://gold@capstonestorage23.blob.core.windows.net",
  mount_point = '/mnt/gold',
  extra_configs = {
    'fs.azure.account.key.capstonestorage23.blob.core.windows.net':'uylHIUmwWqk2jdvsKQyAsd8ei2GDTnnvI7KT0JN0LRd4V/uFWoRd1jiayjDIprn2AX7jF9nrdoOR+ASt+NzuwQ=='
  }
)

In [0]:
df2=spark.createDataFrame(df1)

Storing the output in gold container.

In [0]:

df2.coalesce(1).write.format("com.databricks.spark.csv").option("header", "true").mode("overwrite").save("/mnt/gold/dataframe.csv")

In [0]:

#NH3_Avg=spark.createDataFrame(NH3_Avg) 
AQI_Avg=spark.createDataFrame(AQI_Avg) 
year=spark.createDataFrame(year) 
month=spark.createDataFrame(month) 
ahmedabad =spark.createDataFrame(ahmedabad ) 
Amaravati_year=spark.createDataFrame(Amaravati_year)

In [0]:
CO_Avg.coalesce(1).write.format("com.databricks.spark.csv").option("header", "true").mode("overwrite").save("/mnt/gold/CO_Avg.csv")
NH3_Avg.coalesce(1).write.format("com.databricks.spark.csv").option("header", "true").mode("overwrite").save("/mnt/gold/NH3_Avg.csv")
AQI_Avg.coalesce(1).write.format("com.databricks.spark.csv").option("header", "true").mode("overwrite").save("/mnt/gold/AQI_Avg.csv")
year.coalesce(1).write.format("com.databricks.spark.csv").option("header", "true").mode("overwrite").save("/mnt/gold/year.csv")
month.coalesce(1).write.format("com.databricks.spark.csv").option("header", "true").mode("overwrite").save("/mnt/gold/month.csv")
ahmedabad.coalesce(1).write.format("com.databricks.spark.csv").option("header", "true").mode("overwrite").save("/mnt/gold/ahmedabad.csv")
Amaravati_year.coalesce(1).write.format("com.databricks.spark.csv").option("header", "true").mode("overwrite").save("/mnt/gold/Amaravati_year.csv")

In [0]:
CO_Avg.coalesce(1).write.format("com.databricks.spark.csv").option("header", "true").mode("overwrite").save("/mnt/gold/CO_Avg_Update.csv")

In [0]:
NH3_Avg.coalesce(1).write.format("com.databricks.spark.csv").option("header", "true").mode("overwrite").save("/mnt/gold/NH3_Avg_Update.csv")